# Utiliser une image node officielle
FROM node:18-alpine

# Définir le répertoire de travail dans le container
WORKDIR /app

# Copier package.json & package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install --develop

# Copier le reste des fichiers
COPY . .

# Exposer le port utilisé par le service
EXPOSE 5001

# Lancer le service
CMD ["node", "server.js"]
